### ISSUE TITLE
ruby_rpm_spec_updater - add support to upgrade/downgrade an existing gem dependency

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/polisher#3]
Hypothetically, if my rpm spec depends on rails 4.0.1 already and now I want to upgrade to the latest 5.0.0, it would be great to run:
ruby_rpm_spec_updater.rb ~/rpmbuild/SPECS/rubygem-rails.spec rails-5.0.0.gem

and have it find the existing entry for rails and update it to 5.0.0.

**Comment by mfeifer** [comment]
@jrafanie should this get re-assigned?

**Comment by movitto** [comment]
I would hope so given that its been open for 6 years!

Hope all is well at RedHat/IBM!

**Comment by jrafanie** [comment]
I think we can close it 😉
